### ISSUE TITLE
Test results do not appear until you re-visit the Tests page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#273]
To replicate, enter test results for any test. The data you entered does not appear in the Tests Due page unless you leave Tests container and then re-open it.

**Comment by dubdabasoduba** [comment]
![device-2019-04-15-105144](https://user-images.githubusercontent.com/4817531/56115626-7bd25780-5f6c-11e9-8853-d51adf8cfd6e.png)
@cagulas I can see the tests entered even before the tests container. Unless I got the description for this issue wrong.

**Comment by cagulas** [comment]
Have replicated this and shown the error on my J5. This is not happening on emulator.

**Comment by cagulas** [comment]
18th April:

Still not fixed.

**Comment by dubdabasoduba** [comment]
@cagulas I have fixed this today after using the J5. The field where the results occur didn't have a definite color so on the J5 white would be assigned thus the text would not be visible because the background is also white.

**Comment by cagulas** [comment]
I find these issues so interesting to hear about. Thanks for giving the context on what was causing this.

**Comment by cagulas** [comment]
@dubdabasoduba This doesn't seem to have made it into the latest release. This is still an issue on my J5 phone.
