### ISSUE TITLE
[Ona Support Request]: Native Form Version 2.1.19 not updating Radio Buttons

### ISSUE THREAD

**Issue by MwambaK** [opensrp/opensrp-client-anc#856]
### Affected App or Server Version

v.1.6.8

### What kind of support do you need?

The latest native form (2.1.19) is not allowing the user to change values of radio buttons after entered and saved, current native form downgraded to is 2.1.11 but 2.1.11 does not have the function to stop the user from exiting tests under diagnostic tests and imaging if a required field is left empty.

### What is the acceptance criteria for your support request?

to be able to update radio buttons after exiting a container or passing the step and returning to it as well as be able to not exit a form under diagnostic tests if a field has been left empty.

**Comment by madrinekariuki** [comment]
@SebaMutuku 

This has been tested on `reference-app-debug-zambia`
user: `anc`

Steps:

- login to the apk 
- create a client and start a contact
- fill data for a section e.g Physical Exam  and ensure necessary radio buttons are checked. 
- go to the next section e.g client profile and fill in and finish.
- go back to the physical profile section and confirm that the radio buttons are still selected correctly.

Observation:
The radio buttons remain selected /updated.

**Comment by SebaMutuku** [comment]
@MwambaK can you confirm this issue has been resolved and close the ticket from your end?

**Comment by MwambaK** [comment]
@SebaMutuku @AngelaKabari  issue has been resolved.

**Comment by madrinekariuki** [comment]
re-opening this issue still present on #849 on site characteristics. 

`when you click on edit and change some answers on the questions, you will observe that after saving the data is not changing.`

**Comment by AngelaKabari** [comment]
@SebaMutuku will address this bug when working on [#845](https://github.com/opensrp/opensrp-client-anc/issues/845)
